use_frameworks!
platform :ios, '9.0'

target 'DDPublic_Example' do
  pod 'DDPublic', :path => '../'
#  pod 'DDFeedback'
  pod 'Moya'
  target 'DDPublic_Tests' do
    inherit! :search_paths

    
  end
end
